#!/bin/bash

# +-+-+-+-+-
# VARIABLES
# +-+-+-+-+-

FIRMWARE="BIOS"               # Choose BIOS or UEFI

DRIVE="/dev/sda"              # This drive will be formatted
DRIVE_PART1=${DRIVE}1         # boot partition
DRIVE_PART2=${DRIVE}2         # swap partition
DRIVE_PART3=${DRIVE}3         # root partition

DRIVE_LIVEISO="/dev/sda"                  # This drive will be formatted
DRIVE_LIVEISO_PART1="${DRIVE_LIVEISO}1"   # This is the ext4 partition that will be created for /tmp to mount

MOUNTED_DRIVE_ISO="/mnt/ISO"

LIVE_BUILD_DIR="${MOUNTED_DRIVE_ISO}/archbangretro_liveiso"

TIMEZONE="America/Toronto"   
REGION="en_CA.UTF-8 UTF-8"     
LANGUAGE="en_CA.UTF-8"
KEYMAP="us"

HOSTNAME="archbangretrobox"

ARCH_USER="arch"
USER_PSW="archpsw"
ROOT_PSW="rootpsw"

REFLECTOR_COUNTRY="Canada"

# +-+-+-+-+-+-
# COLOR CODES
# +-+-+-+-+-+-

BLUE='\033[1;34m'
GREEN='\033[1;32m'
CYAN='\033[1;36m'
WHITE='\033[1;37m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
BCK_RED='\033[1;41m'
NC='\033[0m'

# +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
# CUSTOM FILES FOR ARCHBANGRETRO
# 
# Those files will be used during 
# chroot to customize archbangretro
# +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-

ARCHBANGRETRO_FOLDER=/opt/archbangretro

# +-+-+-+-+-+-+-+-
# NVIDIA
#
# Decide if we install the nvidia-340xx driver
# Answer should be "YES" or "NO".
#
# +-+-+-+-+-+-+-+-
 
NVIDIA="NO"
NVIDIA_LEGACY="NO"

# Define the URL of the file and its expected MD5 checksum

ARCHBANGRETRO_FILE_URL=https://sourceforge.net/projects/archbangretro/files/archbangretro.tar.xz
ARCHBANGRETRO_EXPECTED_MD5=7b5fcf993787b58ea24d78692c15fc9a

# Specify the URL of the MANJARO_GPG_FILE
MANJARO_GPG_URL="https://gitlab.manjaro.org/packages/core/manjaro-keyring/-/raw/master/manjaro.gpg"

# Specify the URL of the directory containing the mhwd files from Manjaro
MHWD_URL="https://mirror.csclub.uwaterloo.ca/manjaro/stable/extra/x86_64/"

# REPO LOCATIONS
AURBIN_REPO="/dev/sdb2"
AURBIN_LOCATION="/home/arch/aurbin/"
ARCHLINUX_REPO="/dev/sdb2"

SCRIPTS_DIR=/opt/archbangretro/scripts
CURRENT_DIR=$(pwd)
