#!/bin/bash

# +-+-+-+-+-
# VARIABLES
# +-+-+-+-+-

FIRMWARE="UEFI"                # Choose BIOS or UEFI

DRIVE="/dev/sda"              # This drive will be formatted
DRIVE_PART1=${DRIVE}1         # boot partition
DRIVE_PART2=${DRIVE}2         # swap partition
DRIVE_PART3=${DRIVE}3         # root partition

TIMEZONE="America/Toronto"   
REGION="en_CA.UTF-8 UTF-8"     
LANGUAGE="en_CA.UTF-8"
KEYMAP="us"

HOSTNAME="archbangretrobox"

ARCH_USER="archretrouser"
USER_PSW="archretropsw"
ROOT_PSW="archretroroot"

REFLECTOR_COUNTRY="Canada"

# +-+-+-+-+-+-
# COLOR CODES
# +-+-+-+-+-+-

BLUE='\033[1;34m'
GREEN='\033[1;32m'
CYAN='\033[1;36m'
WHITE='\033[1;37m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
BCK_RED='\033[1;41m'
NC='\033[0m'

# +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
# CUSTOM FILES FOR ARCHBANGRETRO
# 
# Those files will be used during 
# chroot to customize archbangretro
# +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-

ARCHBANGRETRO_FOLDER=/opt/archbangretro

# +-+-+-+-+-+-+-+-
# NVIDIA
#
# Decide if we install the nvidia-340xx driver
# Answer should be "YES" or "NO".
#
# +-+-+-+-+-+-+-+-
 
NVIDIA="NO"
NVIDIA_LEGACY="NO"

# Define the URL of the file and its expected MD5 checksum

ARCHBANGRETRO_FILE_URL=https://sourceforge.net/projects/archbangretro/files/archbangretro.tar.xz
ARCHBANGRETRO_EXPECTED_MD5=d44cd4e9efdb21f0de8e980f28f82fa0

# Specify the URL of the MANJARO_GPG_FILE
MANJARO_GPG_URL="https://gitlab.manjaro.org/packages/core/manjaro-keyring/-/raw/master/manjaro.gpg"

# Specify the URL of the directory containing the mhwd files from Manjaro
MHWD_URL="https://mirror.csclub.uwaterloo.ca/manjaro/stable/extra/x86_64/"

# REPO LOCATION
ARCHBANGRETRO_REPO="192.168.190.150:/media/HDD/archbangretro"
